name: Agente Cazador de Empleo

on:
  schedule:
    # MODO PRUEBA: Se ejecutará DIARIAMENTE a las 8:00 AM UTC
    - cron: '0 8 * * *'
    
    # NOTA: En 4 días, cambia la línea de arriba por esta para que sea cada 15 días:
    # - cron: '0 8 1,15 * *'

  workflow_dispatch: # Permite probarlo manualmente con un botón cuando tú quieras

jobs:
  ejecutar-agente:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install google-genai duckduckgo-search

      - name: Ejecutar Agente
        env:
          GEMINI_API_KEY: ${{ secrets.GAK_U2 }}
        run: python main.py
